//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseAndResultMS.Models
{
    using System;

    public partial class AllocateClassRoom
    {
        public int AllocateClassRoomId { get; set; }
        public int DepartmentId { get; set; }
        public int CourseId { get; set; }
        public int ClassRoomId { get; set; }
        public int WeekId { get; set; }
        public Nullable<System.TimeSpan> ClassStartTime { get; set; }
        public Nullable<System.TimeSpan> ClassEndTime { get; set; }

        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
        public virtual Week Week { get; set; }
    }
}
