//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseAndResultMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSchidule
    {
        public string Code { get; set; }
        public string CourseName { get; set; }
        public string Schidule { get; set; }
        public int DepartmentId { get; set; }
    }
}
