//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseAndResultMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInformation
    {
        public string Code { get; set; }
        public string Title { get; set; }
        public string Semester { get; set; }
        public string Teacher { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public Nullable<int> TeacherId { get; set; }
    }
}
