//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseAndResultMS.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Department
    {
        public int DepartmentId { get; set; }

        [Required]
        public string Code { get; set; }
        [Required]
        public string Name { get; set; }
    }
}
